### ISSUE TITLE
The "products" feed does not include the product options associated with a product.

### ISSUE THREAD

**Issue by robertoldaker** [createdotnet/API-Documentation#2] opened 2015-01-16 14:01 UTC

**Comment by Dayjo** [comment] 2015-01-16 14:42
Essentially a duplicate of https://github.com/createdotnet/API-Documentation/issues/3.

One fix to rule them all.

**Comment by robertoldaker** [comment] 2015-01-16 14:47
No, I think this is a separate issue. 

The "products" feed needs to list what product options and values are available for a given product (along with other data such as price).

The "order products" feed need to list what specific product option(s) were chosen by the customer when making the order.

**Comment by Dayjo** [comment] 2015-01-16 14:49
Ah yes, I see what you mean!

**Comment by Dayjo** [comment] 2015-02-03 17:49
The entire model for products is currently incorrect and needs updating.

**Comment by robertoldaker** [comment] 2015-02-04 18:03
Where are we with this one - is it going to be a bit of a pig to do?

**Comment by Dayjo** [comment] 2015-02-06 11:08
Hi Rob,

It's a little bit of a pig in regards to stock (kind of how we discussed before about option-based stock records versus standard stock). Working on a solution though, hopefully have something for next week!

**Comment by robertoldaker** [comment] 2015-02-06 11:28
Hi Joel,

Not sure if this is of any help but I don;t need any stock information -
just the names of the product options and the set of name/value pairs that
correspond to each option.

This is the last fix required and then I will let Jessica use it in anger.

Rob.

**Comment by Dayjo** [comment] 2015-02-06 16:30
I've managed to put together a fix for this. As per the documentation it will look something like this;

```js
{  
    "product":{  
        "ID":898440,
        "parent_category":123133,
        "title":"Retro T-Shirt",
        "short_description":"Quisque sed arcu quis nunc porttitor rutrum faucibus a nunc.",
        "long_description":"",
        "price":"25.99",
        "sku":"898440",
        "weight":"4.60",
        "stock_number":121,
        "title_tag":"Retro T-Shirt",
        "meta_keywords":"Tshirt, retro, clothing",
        "meta_description":"A retro T-shirt",
        "was_price":"0.00",
        "rrp":"0.00",
        "trade_price":"0.00",
        "options":[  
            {  
                "ID":"137379",
                "title":"Colour",
                "required":"1",
                "items":[  
                    {  
                        "ID":"561041",
                        "title":"Red",
                        "price_adjustment":"0.00",
                        "weight_adjustment":"0.000",
                        "is_custom_input":"0"
                    },
                    {  
                        "ID":"561045",
                        "title":"Blue",
                        "price_adjustment":"0.00",
                        "weight_adjustment":"0.000",
                        "is_custom_input":"0"
                    }
                ]
            }
        ]
    }
}
```

Will try and get this up on Monday for you Rob!

**Comment by robertoldaker** [comment] 2015-02-06 16:38
Great - thanks for this, Joel and have a great weekend.

Hopefully I can get Jessica started on Mon or Tues. She is looking forward
to using it and trying it out as it will save her a lot of time downloading
and uploading files (as she does now).

Regards,

Rob.

**Comment by Dayjo** [comment] 2015-02-09 15:03
This is all live now @robertoldaker! 

Hope this resolves the issue :)

**Comment by robertoldaker** [comment] 2015-02-09 17:15
Thanks Joel. Will be testing it out today and tomorrow.

rob.

**Comment by robertoldaker** [comment] 2015-02-09 20:08
Hi Joel,

I found a couple of small issues ...

Product with id 126242 is including a spurious product option value that
has a title of "null" for the product option "flavour". After look at the
create.net website all of the production option values were there plus this
spurious one.

Product with id 1172898 is returning a product option with a title of
"null" when it should be "£".

access token is:-
8c3c1bcb13397740973a2eab17439975906e3eed386903f1237757e86d80c7de

Apart from that it seems to be ok.

Cheers,

rob.

**Comment by Dayjo** [comment] 2015-02-09 23:00
Imagine the £ will be some sort of encoding issue which I'll see if I get a chance to fix. The other one i'm unsure, possibly still an encoding issue, perhaps in the system it has a character that the JSON doesn't like.

**Comment by robertoldaker** [comment] 2015-02-10 09:19
Hi Joel,

Found a potential issue with single quotes.

This is example json from the product feed for product 907230
{
 "ID": 504280,
 "title": "Tinted \\'Strawberry Shimmer\\'",
 "price_adjustment": "1.00",
  "weight_adjustment": "0.000",
  "is_custom_input": false
}

This is being interpreted as "Tinted \'Strawberry Shimmer\'" i.e. the "\"
is being escaped when I assume its the single quote that needs to be
escaped. Having said that not even sure that single quotes need/should be
escaped at all since double quotes are being used!

Note: this is a different account to the previous issues, token is:-
1f17873abeaa16a9a7a13f90e8e1f3a53e49240be9f253cf5830d3359914ceb5


Rob.

**Comment by robertoldaker** [comment] 2015-02-10 09:33
Found something else about this. The product title is correctly dealing
with single quotes (an example below) - looks like they do not need to be
quoted at all and they fed through correctly.

{
    "ID": 235081,
    "sku": "235081",
    "categories": [
        116307
    ],
    "title": "'Sienna Red' Pigment Colour",
    "short_description": "",
}

Rob.

**Comment by Dayjo** [comment] 2015-02-10 10:26
Hi Rob,

Have resolved the issue of null values, as well as the encoding issue with the £.

As for the slashes, it seems like the `Tinted 'strawberry shimmer'` option is stored in the database with the backslashes. There should only be  single slashes though, we're not doing anything to add slashes in the JSON. As seen here;

![](http://cl.ly/image/0X0u0V051A1u/Image%202015-02-10%20at%2010.26.10%20am.png)

**Comment by robertoldaker** [comment] 2015-02-10 11:19
Hi Joel,

Issue with nulls are resolved now. Thanks.

I just tried adding a product that contained single quotes in its title and
that also used single quotes in an option name and value for the product
option. What I found was.

1) Product title is stored with just single quotes.
2) Product option title and product option value store single quotes with
"\".

I have by-passed the issue in AngelBooks by ripping out the spurious "\"s
but I thought I would raise the issue with you just in case it causes other
issues.

I am ready to try it out with Jessica now.

Are you happy for it to be used? ( i.e. no more imminent changes due?)

Cheers,

Rob.

**Comment by Dayjo** [comment] 2015-02-10 14:32
Hi Rob,

Thanks for the feedback, I've raised the issue with the product option name on our regular issues list as this seems to just be an issue with the options system rather than the API itself. 

Happy for you to use it yeah! We haven't got any plans to change the data models at all, in fact I'm currently working on some internal SDK stuff using the API and these models. 

Obviously if we plan any changes that will affect usage we will let you know ahead of the changes as early as possible!

Happy APIing!

**Closed** 2015-02-10 14:49 UTC
Labels: bug, in progress
